spring:
  application:
    name: auth-service
  jmx:
    default-domain: ${spring.application.name}
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

endpoints:
  refresh:
    enabled: true



